# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cppARorder <- function(mat) {
    .Call(`_biseriatedheatmaps_cppARorder`, mat)
}

cppcorrNeighbor <- function(mat) {
    .Call(`_biseriatedheatmaps_cppcorrNeighbor`, mat)
}

cth_numgroup <- function(cvo) {
    .Call(`_biseriatedheatmaps_cth_numgroup`, cvo)
}

cpprunstest <- function(mat, alternative) {
    .Call(`_biseriatedheatmaps_cpprunstest`, mat, alternative)
}

